package ru.capital.idle.core.game

/**
 * Реальный список богатейших (Forbes Real-Time, июнь 2026): 1020 человек.
 * Состояния в долларах. Разбито на функции-куски из-за лимита размера метода JVM.
 */
object RankingData {

    data class RichPerson(
        val rank: Int,
        val name: String,
        val netWorthUsd: Double,
        val source: String,
        val real: Boolean
    )

    val full: List<RichPerson> by lazy {
        ArrayList<RichPerson>(1020).apply {
            c0(this)
            c1(this)
            c2(this)
            c3(this)
            c4(this)
            c5(this)
            c6(this)
            c7(this)
            c8(this)
        }
    }

    val SIZE: Int get() = full.size

    private fun c0(l: MutableList<RichPerson>) {
        l.add(RichPerson(1, "Elon Musk", 788.8e9, "Tesla, SpaceX", true))
        l.add(RichPerson(2, "Larry Page", 300.5e9, "Google", true))
        l.add(RichPerson(3, "Sergey Brin", 277.2e9, "Google", true))
        l.add(RichPerson(4, "Larry Ellison", 261.4e9, "Oracle", true))
        l.add(RichPerson(5, "Jeff Bezos", 255.5e9, "Amazon", true))
        l.add(RichPerson(6, "Michael Dell", 225.3e9, "Dell Technologies", true))
        l.add(RichPerson(7, "Mark Zuckerberg", 203.6e9, "Facebook", true))
        l.add(RichPerson(8, "Jensen Huang", 177.3e9, "Semiconductors", true))
        l.add(RichPerson(9, "Bernard Arnault & family", 148.3e9, "LVMH", true))
        l.add(RichPerson(10, "Warren Buffett", 144.8e9, "Berkshire Hathaway", true))
        l.add(RichPerson(11, "Amancio Ortega", 141e9, "Zara", true))
        l.add(RichPerson(12, "Rob Walton & family", 137.7e9, "Walmart", true))
        l.add(RichPerson(13, "Jim Walton & family", 135e9, "Walmart", true))
        l.add(RichPerson(14, "Steve Ballmer", 132.4e9, "Microsoft", true))
        l.add(RichPerson(15, "Alice Walton", 126e9, "Walmart", true))
        l.add(RichPerson(16, "Carlos Slim Helu & family", 120.3e9, "Telecom", true))
        l.add(RichPerson(17, "Michael Bloomberg", 109.4e9, "Bloomberg LP", true))
        l.add(RichPerson(18, "Changpeng Zhao", 107.5e9, "Cryptocurrency exchange", true))
        l.add(RichPerson(19, "Bill Gates", 104e9, "Microsoft", true))
        l.add(RichPerson(20, "Thomas Peterffy", 97.3e9, "Discount brokerage", true))
        l.add(RichPerson(21, "Francoise Bettencourt Meyers & family", 93.3e9, "L'Oreal", true))
        l.add(RichPerson(22, "Gautam Adani", 89.8e9, "Infrastructure, commodities", true))
        l.add(RichPerson(23, "Giancarlo Devasini", 89.3e9, "Cryptocurrency", true))
        l.add(RichPerson(24, "Mukesh Ambani", 87.9e9, "Diversified", true))
        l.add(RichPerson(25, "Julia Koch & family", 81.2e9, "Koch, Inc.", true))
        l.add(RichPerson(26, "Masayoshi Son", 81e9, "Telecom, Investments", true))
        l.add(RichPerson(27, "Charles Koch & family", 73.8e9, "Koch, Inc.", true))
        l.add(RichPerson(28, "Zhang Yiming", 69.3e9, "TikTok", true))
        l.add(RichPerson(29, "Jeff Yass", 67.4e9, "Trading, investments", true))
        l.add(RichPerson(30, "Tadashi Yanai & family", 66.7e9, "Fashion retail", true))
        l.add(RichPerson(31, "German Larrea Mota Velasco & family", 62.1e9, "Mining", true))
        l.add(RichPerson(32, "Dieter Schwarz", 61.8e9, "Retail", true))
        l.add(RichPerson(33, "Robin Zeng", 61.5e9, "Batteries", true))
        l.add(RichPerson(34, "Zhong Shanshan", 60.1e9, "Beverages, pharmaceuticals", true))
        l.add(RichPerson(35, "Ken Griffin", 50.4e9, "Hedge funds", true))
        l.add(RichPerson(36, "Iris Fontbona & family", 48.5e9, "Mining", true))
        l.add(RichPerson(37, "Li Ka-shing", 48e9, "Diversified", true))
        l.add(RichPerson(38, "Giovanni Ferrero", 47.7e9, "Nutella, chocolates", true))
        l.add(RichPerson(39, "Ma Huateng", 47.3e9, "Online games", true))
        l.add(RichPerson(40, "Lukas Walton", 46.4e9, "Walmart", true))
        l.add(RichPerson(41, "Gianluigi Aponte", 45.5e9, "Shipping", true))
        l.add(RichPerson(42, "Rafaela Aponte-Diamant", 45.5e9, "Shipping", true))
        l.add(RichPerson(43, "Mark Mateschitz", 44.8e9, "Red Bull", true))
        l.add(RichPerson(44, "Jacqueline Mars", 44.3e9, "Candy, pet food", true))
        l.add(RichPerson(45, "John Mars", 44.3e9, "Candy, pet food", true))
        l.add(RichPerson(46, "Andrea Pignataro", 41.7e9, "Financial software", true))
        l.add(RichPerson(47, "Klaus-Michael Kuehne", 40.9e9, "Shipping", true))
        l.add(RichPerson(48, "Abigail Johnson", 40.5e9, "Fidelity", true))
        l.add(RichPerson(49, "Eric Schmidt", 40.5e9, "Google", true))
        l.add(RichPerson(50, "Gerard Wertheimer", 39.4e9, "Chanel", true))
        l.add(RichPerson(51, "Alain Wertheimer", 39.4e9, "Chanel", true))
        l.add(RichPerson(52, "William Ding", 39.2e9, "Online games", true))
        l.add(RichPerson(53, "Stephen Schwarzman", 38.8e9, "Investments", true))
        l.add(RichPerson(54, "Savitri Jindal & family", 38e9, "Steel", true))
        l.add(RichPerson(55, "Jean-Louis van der Velde", 38e9, "Cryptocurrency", true))
        l.add(RichPerson(56, "Paolo Ardoino", 38e9, "Cryptocurrency", true))
        l.add(RichPerson(57, "Alexey Mordashov & family", 36.9e9, "Steel, investments", true))
        l.add(RichPerson(58, "Henry Samueli", 36.5e9, "Semiconductors", true))
        l.add(RichPerson(59, "Miriam Adelson & family", 35e9, "Casinos", true))
        l.add(RichPerson(60, "He Xiangjian & family", 34.9e9, "Home appliances", true))
        l.add(RichPerson(61, "Eyal Ofer", 33.8e9, "Real estate, shipping", true))
        l.add(RichPerson(62, "Jay Y. Lee", 33.8e9, "Samsung", true))
        l.add(RichPerson(63, "Len Blavatnik", 33.4e9, "Music, chemicals", true))
        l.add(RichPerson(64, "Idan Ofer", 33.2e9, "Shipping", true))
        l.add(RichPerson(65, "Chen Tianshi", 33.1e9, "Semiconductors", true))
        l.add(RichPerson(66, "Eduardo Saverin", 32.9e9, "Facebook", true))
        l.add(RichPerson(67, "Aliko Dangote", 32.8e9, "Cement, sugar", true))
        l.add(RichPerson(68, "Marilyn Simons & family", 32.5e9, "Hedge funds", true))
        l.add(RichPerson(69, "Lakshmi Mittal", 32.1e9, "Steel", true))
        l.add(RichPerson(70, "Andreas von Bechtolsheim & family", 32e9, "Google", true))
        l.add(RichPerson(71, "Lyndal Stephens Greth & family", 31.9e9, "Oil & gas", true))
        l.add(RichPerson(72, "Robert Pera", 31.7e9, "Wireless networking", true))
        l.add(RichPerson(73, "MacKenzie Scott", 31.5e9, "Amazon", true))
        l.add(RichPerson(74, "Pham Nhat Vuong", 31e9, "Diversified", true))
        l.add(RichPerson(75, "Elaine Marshall & family", 30.9e9, "Koch Inc.", true))
        l.add(RichPerson(76, "Michal Strnad", 30.5e9, "Defense Contracting", true))
        l.add(RichPerson(77, "Melinda French Gates", 30.2e9, "Microsoft", true))
        l.add(RichPerson(78, "Thomas Frist Jr & family", 30.2e9, "Hospitals", true))
        l.add(RichPerson(79, "Colin Huang", 30e9, "E-commerce", true))
        l.add(RichPerson(80, "Vinod Adani", 29.9e9, "Infrastructure, commodities", true))
        l.add(RichPerson(81, "Vladimir Potanin", 29.7e9, "Metals", true))
        l.add(RichPerson(82, "Vagit Alekperov", 29.5e9, "Oil", true))
        l.add(RichPerson(83, "Wang Weixiu & family", 28.9e9, "Machinery", true))
        l.add(RichPerson(84, "Leonid Mikhelson & family", 28.3e9, "Gas, chemicals", true))
        l.add(RichPerson(85, "Peter Thiel", 28.3e9, "Facebook, investments", true))
        l.add(RichPerson(86, "John Tu", 28.2e9, "Computer hardware", true))
        l.add(RichPerson(87, "David Sun", 28.2e9, "Computer hardware", true))
        l.add(RichPerson(88, "Huang Shilin", 28.1e9, "Batteries", true))
        l.add(RichPerson(89, "Jack Ma", 27.1e9, "E-commerce", true))
        l.add(RichPerson(90, "Francois Pinault & family", 27e9, "Luxury goods", true))
        l.add(RichPerson(91, "Reinhold Wuerth & family", 26.9e9, "Fasteners", true))
        l.add(RichPerson(92, "Cyrus Poonawalla", 26.8e9, "Vaccines", true))
        l.add(RichPerson(93, "Susanne Klatten", 26.4e9, "BMW, pharmaceuticals", true))
        l.add(RichPerson(94, "Stefan Quandt", 26e9, "BMW", true))
        l.add(RichPerson(95, "Zheng Shuliang & family", 25.9e9, "Aluminum products", true))
        l.add(RichPerson(96, "Israel Englander", 25.8e9, "Hedge funds", true))
        l.add(RichPerson(97, "Shiv Nadar", 25.7e9, "Software services", true))
        l.add(RichPerson(98, "Suleiman Kerimov & family", 25.7e9, "Gold", true))
        l.add(RichPerson(99, "Vladimir Lisin", 25.5e9, "Steel, transport", true))
        l.add(RichPerson(100, "Dilip Shanghvi", 25.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(101, "Gina Rinehart", 25.3e9, "Mining", true))
        l.add(RichPerson(102, "Phil Knight & family", 25.3e9, "Nike", true))
        l.add(RichPerson(103, "Emmanuel Besnier", 25.3e9, "Cheese", true))
        l.add(RichPerson(104, "Vicky Safra & family", 25.2e9, "Banking", true))
        l.add(RichPerson(105, "Stuart Hoegner", 24.7e9, "Cryptocurrency", true))
        l.add(RichPerson(106, "Gennady Timchenko", 24.2e9, "Oil, gas", true))
        l.add(RichPerson(107, "Prince Alwaleed Bin Talal Alsaud", 24.1e9, "Investments", true))
        l.add(RichPerson(108, "David Tepper", 23.7e9, "Hedge funds", true))
        l.add(RichPerson(109, "Henry Nicholas III", 23.6e9, "Semiconductors", true))
        l.add(RichPerson(110, "Rupert Murdoch & family", 23.6e9, "Newspapers, TV network", true))
        l.add(RichPerson(111, "Harry Triguboff", 23.2e9, "Real estate", true))
        l.add(RichPerson(112, "John Doerr", 23.2e9, "Venture capital", true))
        l.add(RichPerson(113, "Christy Walton", 23.1e9, "Walmart", true))
        l.add(RichPerson(114, "Steve Cohen", 23e9, "Hedge funds", true))
        l.add(RichPerson(115, "Stanley Kroenke", 22.2e9, "Sports, real estate", true))
        l.add(RichPerson(116, "Kumar Birla", 22.1e9, "Diversified", true))
        l.add(RichPerson(117, "Wang Chuanfu", 22e9, "Batteries, automobiles", true))
        l.add(RichPerson(118, "Lei Jun", 22e9, "Smartphones, automobiles", true))
        l.add(RichPerson(119, "Takemitsu Takizaki", 22e9, "Sensors", true))
        l.add(RichPerson(120, "Rick Cohen & family", 22e9, "Warehouse automation", true))
    }

    private fun c1(l: MutableList<RichPerson>) {
        l.add(RichPerson(121, "Todd Graves", 22e9, "Fast food", true))
        l.add(RichPerson(122, "Diane Hendricks", 21.7e9, "Building supplies", true))
        l.add(RichPerson(123, "Daniel Gilbert", 21.6e9, "Rocket Mortgage", true))
        l.add(RichPerson(124, "Zhou Qunfei & family", 21.5e9, "Smartphone screens", true))
        l.add(RichPerson(125, "Stefan Persson", 21.4e9, "H&M", true))
        l.add(RichPerson(126, "Ernest Garcia II", 21.4e9, "Used cars", true))
        l.add(RichPerson(127, "Torstein Hagen", 21.2e9, "Cruises", true))
        l.add(RichPerson(128, "Pierre Chen", 21e9, "Electronics", true))
        l.add(RichPerson(129, "Michael Platt", 20.9e9, "Hedge funds", true))
        l.add(RichPerson(130, "John Fredriksen", 20.9e9, "Shipping", true))
        l.add(RichPerson(131, "Dang Yanbao", 20.6e9, "Coal", true))
        l.add(RichPerson(132, "Andrey Melnichenko & family", 20.4e9, "Fertilizers, coal", true))
        l.add(RichPerson(133, "Liu Debing", 20.3e9, "AI", true))
        l.add(RichPerson(134, "Yu Yong", 20.2e9, "Mining", true))
        l.add(RichPerson(135, "Adam Foroughi", 20.1e9, "Advertising technology", true))
        l.add(RichPerson(136, "Harold Hamm & family", 20.1e9, "Oil & gas", true))
        l.add(RichPerson(137, "Renata Kellnerova & family", 19.8e9, "Finance, telecommunications", true))
        l.add(RichPerson(138, "Andrew Forrest & family", 19.7e9, "Mining", true))
        l.add(RichPerson(139, "Philip Anschutz", 19.4e9, "Energy, sports, entertainment", true))
        l.add(RichPerson(140, "Jorge Paulo Lemann & family", 19.2e9, "Beer", true))
        l.add(RichPerson(141, "Donald Bren", 19.2e9, "Real estate", true))
        l.add(RichPerson(142, "Brett Adcock", 19.1e9, "Robots", true))
        l.add(RichPerson(143, "Jerry Jones & family", 18.9e9, "Dallas Cowboys", true))
        l.add(RichPerson(144, "Nik Storonsky", 18.8e9, "Fintech", true))
        l.add(RichPerson(145, "Nancy Walton Laurie", 18.7e9, "Walmart", true))
        l.add(RichPerson(146, "Jason Chang", 18.5e9, "Semiconductors", true))
        l.add(RichPerson(147, "Zou Zhinong & family", 18.3e9, "Telecom equipment", true))
        l.add(RichPerson(148, "Sarath Ratanavadi", 18.3e9, "Energy", true))
        l.add(RichPerson(149, "Chen Jianhua", 18e9, "Chemicals", true))
        l.add(RichPerson(150, "James Ratcliffe", 18e9, "Chemicals", true))
        l.add(RichPerson(151, "Georg Schaeffler", 18e9, "Auto parts", true))
        l.add(RichPerson(152, "Edwin Chen", 18e9, "Artificial intelligence", true))
        l.add(RichPerson(153, "Yuan Fugen & family", 17.9e9, "Metal processing", true))
        l.add(RichPerson(154, "Eric Smidt", 17.9e9, "Hardware stores", true))
        l.add(RichPerson(155, "Kwong Siu-hing", 17.8e9, "Real estate", true))
        l.add(RichPerson(156, "Dhanin Chearavanont", 17.8e9, "Diversified", true))
        l.add(RichPerson(157, "Nathan Kirsh", 17.7e9, "Retail, real estate", true))
        l.add(RichPerson(158, "Enrique Razon Jr.", 17.6e9, "Ports", true))
        l.add(RichPerson(159, "Lu Xiangyang", 17.5e9, "Automobiles, batteries", true))
        l.add(RichPerson(160, "Patrick Collison", 17.5e9, "Payment software", true))
        l.add(RichPerson(161, "John Collison", 17.5e9, "Payment software", true))
        l.add(RichPerson(162, "Eric Li", 17.3e9, "Automobiles", true))
        l.add(RichPerson(163, "Ludwig Merckle", 17.3e9, "Pharmaceuticals", true))
        l.add(RichPerson(164, "Karl Albrecht Jr. & family", 17.1e9, "Supermarkets", true))
        l.add(RichPerson(165, "Beate Heister", 17.1e9, "Supermarkets", true))
        l.add(RichPerson(166, "Stephen Ross", 17e9, "Real estate", true))
        l.add(RichPerson(167, "Pei Zhenhua", 17e9, "Batteries", true))
        l.add(RichPerson(168, "Barry Lam", 16.9e9, "Electronics", true))
        l.add(RichPerson(169, "Jan Koum", 16.9e9, "WhatsApp", true))
        l.add(RichPerson(170, "Arthur Dantchik", 16.9e9, "Trading, investments", true))
        l.add(RichPerson(171, "Anders Holch Povlsen", 16.7e9, "Fashion retail", true))
        l.add(RichPerson(172, "Wang Liping & family", 16.4e9, "Hydraulic machinery", true))
        l.add(RichPerson(173, "Terry Gou", 16.4e9, "Electronics", true))
        l.add(RichPerson(174, "Mikhail Fridman", 16.3e9, "Oil, banking, telecom", true))
        l.add(RichPerson(175, "Alejandro Bailleres Gual & family", 16.2e9, "Diversified", true))
        l.add(RichPerson(176, "Charles Ergen", 16.2e9, "Satellite TV", true))
        l.add(RichPerson(177, "Peter Mallouk", 16.1e9, "Wealth planning", true))
        l.add(RichPerson(178, "Jack Dangermond", 16.1e9, "Mapping software", true))
        l.add(RichPerson(179, "Theo Albrecht Jr & family", 16e9, "Aldi, Trader Joe's", true))
        l.add(RichPerson(180, "Johann Rupert & family", 15.9e9, "Luxury goods", true))
        l.add(RichPerson(181, "Radhakishan Damani", 15.9e9, "Retail, investments", true))
        l.add(RichPerson(182, "Edward Johnson IV", 15.9e9, "Fidelity", true))
        l.add(RichPerson(183, "Qin Yinglin", 15.8e9, "Pig breeding", true))
        l.add(RichPerson(184, "George Kaiser", 15.7e9, "Oil & gas, banking", true))
        l.add(RichPerson(185, "Wang Wei", 15.6e9, "Package delivery", true))
        l.add(RichPerson(186, "John Menard Jr", 15.6e9, "Home improvement stores", true))
        l.add(RichPerson(187, "Bruce Cheng", 15.6e9, "Electronics", true))
        l.add(RichPerson(188, "Jack Clark", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(189, "Tom Brown", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(190, "Jared Kaplan", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(191, "Dario Amodei", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(192, "Christopher Olah", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(193, "Sam McCandlish", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(194, "Daniela Amodei", 15.5e9, "Artificial intelligence", true))
        l.add(RichPerson(195, "Charlene de Carvalho-Heineken & family", 15.4e9, "Heineken", true))
        l.add(RichPerson(196, "Jaime Gilinski Bacal", 15.4e9, "Banking", true))
        l.add(RichPerson(197, "Ray Dalio", 15.4e9, "Hedge funds", true))
        l.add(RichPerson(198, "Zhong Huijuan", 15.4e9, "Pharmaceuticals", true))
        l.add(RichPerson(199, "Hussain Sajwani", 15.3e9, "Real estate", true))
        l.add(RichPerson(200, "Friedhelm Loh", 15.1e9, "Manufacturing", true))
        l.add(RichPerson(201, "Laurene Powell Jobs", 15e9, "Apple, Disney", true))
        l.add(RichPerson(202, "Abdulsamad Rabiu", 15e9, "Cement, sugar", true))
        l.add(RichPerson(203, "Shahid Khan", 14.9e9, "Sports teams, auto parts", true))
        l.add(RichPerson(204, "James Dyson", 14.9e9, "Vacuums", true))
        l.add(RichPerson(205, "Prajogo Pangestu", 14.7e9, "Petrochemicals, energy", true))
        l.add(RichPerson(206, "Xavier Niel & family", 14.7e9, "Internet, telecom", true))
        l.add(RichPerson(207, "Vinod Khosla", 14.4e9, "Sun Microsystems, venture capital", true))
        l.add(RichPerson(208, "Wang Laisheng", 14.4e9, "Electronics components", true))
        l.add(RichPerson(209, "Ivan Glasenberg", 14.3e9, "Mining", true))
        l.add(RichPerson(210, "Joseph Lau", 14.2e9, "Real estate", true))
        l.add(RichPerson(211, "Ralph Lauren & family", 14.2e9, "Apparel", true))
        l.add(RichPerson(212, "Zhang Zhidong", 14.2e9, "Online games", true))
        l.add(RichPerson(213, "Wang Laichun", 14.1e9, "Electronics components", true))
        l.add(RichPerson(214, "Ann Walton Kroenke", 14.1e9, "Walmart", true))
        l.add(RichPerson(215, "Alisher Usmanov", 14.1e9, "Steel, telecom, investments", true))
        l.add(RichPerson(216, "Elizabeth Johnson", 14e9, "Fidelity", true))
        l.add(RichPerson(217, "James Goodnight", 14e9, "Software", true))
        l.add(RichPerson(218, "Cao Renxian", 14e9, "Photovoltaic equipment", true))
        l.add(RichPerson(219, "Brad Jacobs", 13.9e9, "Logistics", true))
        l.add(RichPerson(220, "Robert Kraft", 13.8e9, "Manufacturing, New England Patriots", true))
        l.add(RichPerson(221, "Low Tuck Kwong", 13.7e9, "Coal", true))
        l.add(RichPerson(222, "Wang Ning & family", 13.7e9, "Toys", true))
        l.add(RichPerson(223, "Dmitri Bukhman", 13.6e9, "Online games", true))
        l.add(RichPerson(224, "Igor Bukhman", 13.6e9, "Online games", true))
        l.add(RichPerson(225, "Antonia Ax:son Johnson & family", 13.5e9, "Diversified", true))
        l.add(RichPerson(226, "Leon Black", 13.4e9, "Private equity", true))
        l.add(RichPerson(227, "Simon Reuben", 13.2e9, "Real estate, investments", true))
        l.add(RichPerson(228, "David Reuben", 13.2e9, "Investments, real estate", true))
        l.add(RichPerson(229, "Ken Fisher", 13.2e9, "Money management", true))
        l.add(RichPerson(230, "Hasso Plattner & family", 13.1e9, "Software", true))
        l.add(RichPerson(231, "J. Christopher Reyes", 13.1e9, "Food distribution", true))
        l.add(RichPerson(232, "Jude Reyes", 13.1e9, "Food distribution", true))
        l.add(RichPerson(233, "Li Shuirong & family", 13.1e9, "Petrochemicals", true))
        l.add(RichPerson(234, "Sunil Mittal", 13.1e9, "Telecom", true))
        l.add(RichPerson(235, "Robert Kuok", 13e9, "Palm oil, shipping, property", true))
        l.add(RichPerson(236, "Alexander Karp", 13e9, "Software firm", true))
        l.add(RichPerson(237, "George Roberts", 12.9e9, "Private equity", true))
        l.add(RichPerson(238, "Ravi Jaipuria", 12.9e9, "Soft drinks, fast food", true))
        l.add(RichPerson(239, "Orlando Bravo", 12.8e9, "Private equity", true))
        l.add(RichPerson(240, "Uday Kotak", 12.8e9, "Banking", true))
    }

    private fun c2(l: MutableList<RichPerson>) {
        l.add(RichPerson(241, "Peter Woo", 12.8e9, "Real estate", true))
        l.add(RichPerson(242, "Richard Kinder", 12.8e9, "Pipelines", true))
        l.add(RichPerson(243, "R. Budi Hartono", 12.7e9, "Banking, tobacco", true))
        l.add(RichPerson(244, "Sandra Ortega Mera", 12.6e9, "Zara", true))
        l.add(RichPerson(245, "Michael Sabel", 12.6e9, "Oil & gas", true))
        l.add(RichPerson(246, "Robert Pender", 12.6e9, "Oil & gas", true))
        l.add(RichPerson(247, "Lee Boo-jin", 12.5e9, "Samsung", true))
        l.add(RichPerson(248, "Joseph Tsai", 12.5e9, "E-commerce", true))
        l.add(RichPerson(249, "David Steward", 12.4e9, "IT provider", true))
        l.add(RichPerson(250, "Charles Schwab", 12.4e9, "Discount brokerage", true))
        l.add(RichPerson(251, "Hamdi Ulukaya", 12.4e9, "Greek yogurt", true))
        l.add(RichPerson(252, "Dan Cathy", 12.3e9, "Chick-fil-A", true))
        l.add(RichPerson(253, "Trudy Cathy White", 12.3e9, "Chick-fil-A", true))
        l.add(RichPerson(254, "Bubba Cathy", 12.3e9, "Chick-fil-A", true))
        l.add(RichPerson(255, "Pierre Omidyar", 12.3e9, "EBay, PayPal", true))
        l.add(RichPerson(256, "Andrew Beal", 12.3e9, "Banks, real estate", true))
        l.add(RichPerson(257, "Wang Xin", 12.1e9, "Manufacturing", true))
        l.add(RichPerson(258, "Francine von Finck & family", 12e9, "Investments", true))
        l.add(RichPerson(259, "Viatcheslav Kantor", 12e9, "Fertilizer, real estate", true))
        l.add(RichPerson(260, "Jim Pattison", 11.9e9, "Diversified", true))
        l.add(RichPerson(261, "Alexander Gerko", 11.9e9, "Trading", true))
        l.add(RichPerson(262, "Henry Kravis", 11.9e9, "Private equity", true))
        l.add(RichPerson(263, "Douglas Leone", 11.8e9, "Venture capital", true))
        l.add(RichPerson(264, "Christopher Hohn", 11.8e9, "Hedge funds", true))
        l.add(RichPerson(265, "David Velez & family", 11.8e9, "Fintech", true))
        l.add(RichPerson(266, "Li Ping", 11.8e9, "Batteries", true))
        l.add(RichPerson(267, "Riley Bechtel & family", 11.8e9, "Engineering, construction", true))
        l.add(RichPerson(268, "Lee Seo-hyun", 11.7e9, "Samsung", true))
        l.add(RichPerson(269, "Cai Huabo", 11.7e9, "Electronics", true))
        l.add(RichPerson(270, "Hong Ra-hee", 11.6e9, "Samsung", true))
        l.add(RichPerson(271, "Zhang Hejun", 11.6e9, "Electronics", true))
        l.add(RichPerson(272, "Chris Larsen", 11.6e9, "Cryptocurrency", true))
        l.add(RichPerson(273, "Mark Stevens", 11.6e9, "Venture capital", true))
        l.add(RichPerson(274, "Ernesto Bertarelli", 11.5e9, "Biotech, investments", true))
        l.add(RichPerson(275, "Liang Wenfeng", 11.5e9, "AI, hedge fund", true))
        l.add(RichPerson(276, "Kushal Pal Singh", 11.4e9, "Real estate", true))
        l.add(RichPerson(277, "Finn Rausing", 11.4e9, "Packaging", true))
        l.add(RichPerson(278, "Kirsten Rausing", 11.4e9, "Packaging", true))
        l.add(RichPerson(279, "Jorn Rausing", 11.4e9, "Packaging", true))
        l.add(RichPerson(280, "Tsai Ming-kai", 11.4e9, "Semiconductors", true))
        l.add(RichPerson(281, "Dan Friedkin", 11.4e9, "Toyota dealerships", true))
        l.add(RichPerson(282, "Liu Yongxing", 11.4e9, "Diversified", true))
        l.add(RichPerson(283, "Antony Ressler", 11.3e9, "Finance", true))
        l.add(RichPerson(284, "Charoen Sirivadhanabhakdi & family", 11.1e9, "Beverage, Real Estate", true))
        l.add(RichPerson(285, "Charles Butt", 11.1e9, "Supermarkets", true))
        l.add(RichPerson(286, "Juan Carlos Escotet", 11.1e9, "Banking", true))
        l.add(RichPerson(287, "Chen Tao & family", 11.1e9, "Hardware", true))
        l.add(RichPerson(288, "Valerie Mars", 11.1e9, "Candy, pet food", true))
        l.add(RichPerson(289, "Victoria Mars", 11.1e9, "Candy, pet food", true))
        l.add(RichPerson(290, "Marijke Mars", 11.1e9, "Candy, pet food", true))
        l.add(RichPerson(291, "Pamela Mars", 11.1e9, "Candy, pet food", true))
        l.add(RichPerson(292, "Gabe Newell", 11e9, "Video games", true))
        l.add(RichPerson(293, "John Malone", 11e9, "Cable television", true))
        l.add(RichPerson(294, "Mikhail Prokhorov", 11e9, "Investments", true))
        l.add(RichPerson(295, "Francesco Gaetano Caltagirone", 10.9e9, "Cement, diversified", true))
        l.add(RichPerson(296, "Robert Duggan", 10.9e9, "Pharmaceuticals", true))
        l.add(RichPerson(297, "Martin Lorentzon", 10.9e9, "Spotify", true))
        l.add(RichPerson(298, "Andreas Struengmann & family", 10.8e9, "Pharmaceuticals", true))
        l.add(RichPerson(299, "Thomas Struengmann & family", 10.8e9, "Pharmaceuticals", true))
        l.add(RichPerson(300, "Tilman Fertitta", 10.8e9, "Entertainment, Houston Rockets", true))
        l.add(RichPerson(301, "Andre Esteves", 10.8e9, "Banking", true))
        l.add(RichPerson(302, "Gong Hongjia & family", 10.8e9, "Video surveillance", true))
        l.add(RichPerson(303, "Ramzi Musallam", 10.8e9, "Private equity", true))
        l.add(RichPerson(304, "Andrei Guryev & family", 10.8e9, "Fertilizers", true))
        l.add(RichPerson(305, "Josh Harris", 10.8e9, "Private equity", true))
        l.add(RichPerson(306, "Johann Graf", 10.8e9, "Gambling", true))
        l.add(RichPerson(307, "Michael Federmann & family", 10.7e9, "Defense, hotels", true))
        l.add(RichPerson(308, "George Kurtz", 10.7e9, "Security software", true))
        l.add(RichPerson(309, "Vikram Lal & family", 10.7e9, "Motorcycles", true))
        l.add(RichPerson(310, "Sherry Brydson", 10.7e9, "Thomson Reuters", true))
        l.add(RichPerson(311, "Rafael Del Pino", 10.7e9, "Construction", true))
        l.add(RichPerson(312, "Nadia Thiele & family", 10.6e9, "Investments", true))
        l.add(RichPerson(313, "Carrie Perrodo & family", 10.6e9, "Oil", true))
        l.add(RichPerson(314, "Nicky Oppenheimer & family", 10.6e9, "Diamonds", true))
        l.add(RichPerson(315, "Wu Jianshu", 10.6e9, "Auto parts", true))
        l.add(RichPerson(316, "German Khan", 10.5e9, "Oil, banking, telecom", true))
        l.add(RichPerson(317, "Luis Carlos Sarmiento", 10.5e9, "Banking", true))
        l.add(RichPerson(318, "Thomas Schmidheiny", 10.5e9, "Cement", true))
        l.add(RichPerson(319, "Vincent Bollore & family", 10.5e9, "Investments", true))
        l.add(RichPerson(320, "Randa Duncan Williams", 10.5e9, "Pipelines", true))
        l.add(RichPerson(321, "Magdalena Martullo-Blocher", 10.4e9, "Chemicals", true))
        l.add(RichPerson(322, "Dannine Avara", 10.4e9, "Pipelines", true))
        l.add(RichPerson(323, "Milane Frantz", 10.4e9, "Pipelines", true))
        l.add(RichPerson(324, "Jeffery Hildebrand", 10.4e9, "Oil & gas", true))
        l.add(RichPerson(325, "Jimmy Haslam", 10.3e9, "Gas stations, retail", true))
        l.add(RichPerson(326, "Carl Cook", 10.3e9, "Medical devices", true))
        l.add(RichPerson(327, "Leonid Fedun", 10.3e9, "Oil", true))
        l.add(RichPerson(328, "Sun Piaoyang", 10.3e9, "Pharmaceuticals", true))
        l.add(RichPerson(329, "Charlie Mills", 10.2e9, "Medical supplies", true))
        l.add(RichPerson(330, "Qi Shi & family", 10.2e9, "Financial information", true))
        l.add(RichPerson(331, "Arthur Blank", 10.2e9, "Home Depot", true))
        l.add(RichPerson(332, "Ernest Garcia III", 10.2e9, "Used cars", true))
        l.add(RichPerson(333, "Theo Mueller", 10.2e9, "Dairy", true))
        l.add(RichPerson(334, "Anthony Pratt", 10.1e9, "Manufacturing", true))
        l.add(RichPerson(335, "Scott Duncan", 10.1e9, "Pipelines", true))
        l.add(RichPerson(336, "Karel Komarek", 10.1e9, "Oil and gas, IT, lotteries", true))
        l.add(RichPerson(337, "Tom Gores", 10.1e9, "Private equity", true))
        l.add(RichPerson(338, "Robert F. Smith", 10e9, "Private equity", true))
        l.add(RichPerson(339, "David Cheriton", 10e9, "Google", true))
        l.add(RichPerson(340, "Ling Tang", 10e9, "Advertising technology", true))
        l.add(RichPerson(341, "Ken Xie & family", 10e9, "Cybersecurity", true))
        l.add(RichPerson(342, "Michael Kim", 9.9e9, "Private equity", true))
        l.add(RichPerson(343, "Daniel Kretinsky", 9.9e9, "Energy, investments", true))
        l.add(RichPerson(344, "Anthoni Salim", 9.9e9, "Diversified", true))
        l.add(RichPerson(345, "Murali Divi & family", 9.9e9, "Pharmaceuticals", true))
        l.add(RichPerson(346, "Dustin Moskovitz", 9.9e9, "Facebook", true))
        l.add(RichPerson(347, "Harry Stine & family", 9.9e9, "Agriculture", true))
        l.add(RichPerson(348, "Graeme Hart", 9.9e9, "Packaging", true))
        l.add(RichPerson(349, "Ken Langone", 9.9e9, "Investments", true))
        l.add(RichPerson(350, "Tobi Lutke", 9.8e9, "E-commerce", true))
        l.add(RichPerson(351, "Micky Arison", 9.8e9, "Carnival Cruises", true))
        l.add(RichPerson(352, "Iskander Makhmudov", 9.7e9, "Mining, metals, machinery", true))
        l.add(RichPerson(353, "Kjell Inge Rokke", 9.7e9, "Shipping, seafood", true))
        l.add(RichPerson(354, "Nassef Sawiris", 9.7e9, "Construction, investments", true))
        l.add(RichPerson(355, "Pauline MacMillan Keinath", 9.6e9, "Cargill", true))
        l.add(RichPerson(356, "Carl Bennet", 9.6e9, "Investments", true))
        l.add(RichPerson(357, "Judy Faulkner", 9.6e9, "Healthcare software", true))
        l.add(RichPerson(358, "Daniel Ek", 9.6e9, "Spotify", true))
        l.add(RichPerson(359, "Michael Rubin", 9.6e9, "Online retail", true))
        l.add(RichPerson(360, "Sulaiman Al Habib", 9.6e9, "Hospital group", true))
    }

    private fun c3(l: MutableList<RichPerson>) {
        l.add(RichPerson(361, "Lin Muqin & family", 9.5e9, "Beverages", true))
        l.add(RichPerson(362, "Morris Chang", 9.5e9, "Semiconductors", true))
        l.add(RichPerson(363, "Daniel Tsai", 9.5e9, "Finance", true))
        l.add(RichPerson(364, "Fernando Roberto Moreira Salles", 9.5e9, "Banking, minerals", true))
        l.add(RichPerson(365, "Brian Chesky", 9.4e9, "Airbnb", true))
        l.add(RichPerson(366, "Georg Stumpf", 9.4e9, "Real estate, construction", true))
        l.add(RichPerson(367, "Zhang Xuexin & family", 9.4e9, "Aluminum", true))
        l.add(RichPerson(368, "Fredrik Lundberg", 9.4e9, "Real estate, investments", true))
        l.add(RichPerson(369, "Law Kar Po", 9.4e9, "Real estate", true))
        l.add(RichPerson(370, "Roman Abramovich & family", 9.3e9, "Steel, investments", true))
        l.add(RichPerson(371, "Dirk Rossmann & family", 9.3e9, "Drugstores", true))
        l.add(RichPerson(372, "Viktor Rashnikov", 9.3e9, "Steel", true))
        l.add(RichPerson(373, "Viktor Vekselberg", 9.3e9, "Metals, investments", true))
        l.add(RichPerson(374, "Terrence Pegula", 9.3e9, "Natural gas", true))
        l.add(RichPerson(375, "Zeng Fangqin", 9.3e9, "Smartphone components", true))
        l.add(RichPerson(376, "Pankaj Patel", 9.3e9, "Pharmaceuticals", true))
        l.add(RichPerson(377, "Maria Asuncion Aramburuzabala & family", 9.3e9, "Beer, investments", true))
        l.add(RichPerson(378, "Todd Boehly", 9.3e9, "Finance", true))
        l.add(RichPerson(379, "David Duffield", 9.2e9, "Business software", true))
        l.add(RichPerson(380, "Wei Jianjun & family", 9.2e9, "Automobiles", true))
        l.add(RichPerson(381, "David Geffen", 9.2e9, "Movies, record labels", true))
        l.add(RichPerson(382, "Lin Bin", 9.1e9, "Smartphones", true))
        l.add(RichPerson(383, "Les Wexner & family", 9.1e9, "Retail", true))
        l.add(RichPerson(384, "Neil Bluhm", 9.1e9, "Real estate", true))
        l.add(RichPerson(385, "Li Xiting", 9.1e9, "Medical devices", true))
        l.add(RichPerson(386, "Mong-Koo Chung", 9.1e9, "Hyundai", true))
        l.add(RichPerson(387, "Blair Parry-Okeden", 9.1e9, "Media, automotive", true))
        l.add(RichPerson(388, "Chen Dongsheng", 9.1e9, "Insurance", true))
        l.add(RichPerson(389, "Anthony Bamford & family", 9.1e9, "Construction equipment", true))
        l.add(RichPerson(390, "Richard Tsai", 9.1e9, "Finance", true))
        l.add(RichPerson(391, "Bruce Kovner", 9e9, "Hedge funds", true))
        l.add(RichPerson(392, "Elisabeth DeLuca & family", 9e9, "Subway", true))
        l.add(RichPerson(393, "Jim Kennedy", 9e9, "Media, automotive", true))
        l.add(RichPerson(394, "Eric Wittouck", 9e9, "Investments", true))
        l.add(RichPerson(395, "Jeff Greene", 9e9, "Real estate, investments", true))
        l.add(RichPerson(396, "Juan Roig", 9e9, "Supermarkets", true))
        l.add(RichPerson(397, "Robert Rowling", 9e9, "Hotels, investments", true))
        l.add(RichPerson(398, "Lin Tsung-Chi", 8.9e9, "Furniture rails", true))
        l.add(RichPerson(399, "Zhu Yi", 8.9e9, "Pharmaceuticals", true))
        l.add(RichPerson(400, "Nathan Blecharczyk", 8.9e9, "Airbnb", true))
        l.add(RichPerson(401, "Pavel Tykac", 8.9e9, "Coal mines", true))
        l.add(RichPerson(402, "William Ackman", 8.9e9, "Hedge funds", true))
        l.add(RichPerson(403, "Zhou Chaonan", 8.9e9, "Manufacturing", true))
        l.add(RichPerson(404, "Marie Besnier Beauvalot", 8.8e9, "Cheese", true))
        l.add(RichPerson(405, "Jean-Michel Besnier", 8.8e9, "Cheese", true))
        l.add(RichPerson(406, "David Shaw", 8.8e9, "Hedge funds", true))
        l.add(RichPerson(407, "Pedro Moreira Salles", 8.8e9, "Banking, minerals", true))
        l.add(RichPerson(408, "Frank Lowy", 8.8e9, "Investments", true))
        l.add(RichPerson(409, "Tamara Gustavson", 8.7e9, "Self storage", true))
        l.add(RichPerson(410, "Yuri Milner", 8.7e9, "Tech investments", true))
        l.add(RichPerson(411, "Lynsi Snyder", 8.7e9, "In-N-Out Burger", true))
        l.add(RichPerson(412, "Leo KoGuan", 8.7e9, "IT provider", true))
        l.add(RichPerson(413, "Patrick Soon-Shiong", 8.6e9, "Pharmaceuticals", true))
        l.add(RichPerson(414, "Yi Zheng", 8.6e9, "Software", true))
        l.add(RichPerson(415, "Rajan Mittal", 8.6e9, "Telecom", true))
        l.add(RichPerson(416, "John Morris", 8.5e9, "Sporting goods retail", true))
        l.add(RichPerson(417, "Rakesh Mittal", 8.5e9, "Telecom", true))
        l.add(RichPerson(418, "Sri Prakash Lohia", 8.5e9, "Petrochemicals", true))
        l.add(RichPerson(419, "Michael Xie", 8.5e9, "Cybersecurity", true))
        l.add(RichPerson(420, "Justin Sun", 8.5e9, "Cryptocurrency", true))
        l.add(RichPerson(421, "You Xiaoping & family", 8.5e9, "Polyurethanes", true))
        l.add(RichPerson(422, "Liang Wengen", 8.5e9, "Construction equipment", true))
        l.add(RichPerson(423, "Denise York & family", 8.5e9, "San Francisco 49ers", true))
        l.add(RichPerson(424, "Michael Dorrell", 8.5e9, "Investing", true))
        l.add(RichPerson(425, "Mike Cannon-Brookes", 8.5e9, "Software", true))
        l.add(RichPerson(426, "Leonid Boguslavsky", 8.4e9, "Venture capital", true))
        l.add(RichPerson(427, "Stephen Bisciotti", 8.4e9, "Staffing, Baltimore Ravens", true))
        l.add(RichPerson(428, "Tench Coxe", 8.4e9, "Venture capital", true))
        l.add(RichPerson(429, "Jean Salata", 8.4e9, "Finance", true))
        l.add(RichPerson(430, "Laurent Dassault", 8.4e9, "Diversified", true))
        l.add(RichPerson(431, "Odd Reitan & family", 8.4e9, "Retail, real estate", true))
        l.add(RichPerson(432, "Leonard Stern", 8.3e9, "Real estate", true))
        l.add(RichPerson(433, "Roger Penske", 8.3e9, "Cars", true))
        l.add(RichPerson(434, "Thierry Dassault", 8.3e9, "Diversified", true))
        l.add(RichPerson(435, "Marie-Helene Habert-Dassault", 8.3e9, "Diversified", true))
        l.add(RichPerson(436, "Azim Premji", 8.3e9, "Software services", true))
        l.add(RichPerson(437, "Alexei Kuzmichev", 8.2e9, "Oil, banking, telecom", true))
        l.add(RichPerson(438, "Wang Yusuo & family", 8.2e9, "Natural gas distribution", true))
        l.add(RichPerson(439, "Massimiliana Landini Aleotti & family", 8.2e9, "Pharmaceuticals", true))
        l.add(RichPerson(440, "J. Joe Ricketts & family", 8.2e9, "TD Ameritrade", true))
        l.add(RichPerson(441, "Denise Coates", 8.2e9, "Online gambling", true))
        l.add(RichPerson(442, "Yitzhak Tshuva", 8.2e9, "Real estate", true))
        l.add(RichPerson(443, "Thomas Kirk Kristiansen", 8.2e9, "Lego", true))
        l.add(RichPerson(444, "Sofie Kirk Kristiansen", 8.2e9, "Lego", true))
        l.add(RichPerson(445, "Agnete Kirk Thinggaard", 8.2e9, "Lego", true))
        l.add(RichPerson(446, "Don Hankey", 8.2e9, "Auto loans", true))
        l.add(RichPerson(447, "Rekha Jhunjhunwala", 8.1e9, "Investments", true))
        l.add(RichPerson(448, "Tatyana Kim", 8.1e9, "E-commerce", true))
        l.add(RichPerson(449, "Scott Farquhar", 8.1e9, "Software", true))
        l.add(RichPerson(450, "Joe Gebbia", 8.1e9, "Airbnb", true))
        l.add(RichPerson(451, "Paul Tudor Jones II", 8.1e9, "Hedge funds", true))
        l.add(RichPerson(452, "Tsai Hong-tu", 8.1e9, "Finance", true))
        l.add(RichPerson(453, "Ty Warner", 8.1e9, "Plush toys, real estate", true))
        l.add(RichPerson(454, "Lin Li", 8e9, "Investments", true))
        l.add(RichPerson(455, "Maximilian Viessmann", 8e9, "Heating, cooling equipment", true))
        l.add(RichPerson(456, "Zhang Wanzhen", 8e9, "Electronics components", true))
        l.add(RichPerson(457, "Michael Moritz", 8e9, "Venture capital", true))
        l.add(RichPerson(458, "Igor Olenicoff", 8e9, "Real estate", true))
        l.add(RichPerson(459, "Ron Baron", 8e9, "Money management", true))
        l.add(RichPerson(460, "Thomas Pritzker", 8e9, "Hotels, investments", true))
        l.add(RichPerson(461, "Kelcy Warren", 8e9, "Pipelines", true))
        l.add(RichPerson(462, "David Siegel", 8e9, "Hedge funds", true))
        l.add(RichPerson(463, "John Overdeck", 8e9, "Hedge funds", true))
        l.add(RichPerson(464, "Andreas Halvorsen", 8e9, "Hedge funds", true))
        l.add(RichPerson(465, "Thai Lee", 8e9, "IT provider", true))
        l.add(RichPerson(466, "Francis Choi", 8e9, "Real estate", true))
        l.add(RichPerson(467, "Jonathan Gray", 7.9e9, "Investments", true))
        l.add(RichPerson(468, "Gayle Benson", 7.9e9, "New Orleans Saints", true))
        l.add(RichPerson(469, "Rahel Blocher", 7.9e9, "Chemicals", true))
        l.add(RichPerson(470, "Jacques Saade Jr", 7.9e9, "Shipping", true))
        l.add(RichPerson(471, "Tanya Saade Zeenny", 7.9e9, "Shipping", true))
        l.add(RichPerson(472, "Rodolphe Saade", 7.9e9, "Shipping", true))
        l.add(RichPerson(473, "Paolo Rocca", 7.9e9, "Pipe Manufacturing", true))
        l.add(RichPerson(474, "Gianfelice Rocca", 7.9e9, "Pipe Manufacturing", true))
        l.add(RichPerson(475, "Tsai Cheng-ta", 7.9e9, "Finance", true))
        l.add(RichPerson(476, "Philippe Laffont", 7.9e9, "Hedge fund", true))
        l.add(RichPerson(477, "Alexandra Schoerghuber & family", 7.9e9, "Real estate", true))
        l.add(RichPerson(478, "Tahir & family", 7.9e9, "Diversified", true))
        l.add(RichPerson(479, "Viktor Kharitonin", 7.9e9, "Pharmaceuticals", true))
        l.add(RichPerson(480, "Guillaume Pousaz", 7.8e9, "Fintech", true))
    }

    private fun c4(l: MutableList<RichPerson>) {
        l.add(RichPerson(481, "Sudhir Mehta", 7.8e9, "Pharmaceuticals, power", true))
        l.add(RichPerson(482, "Samir Mehta", 7.8e9, "Pharmaceuticals, power", true))
        l.add(RichPerson(483, "Vyacheslav Kim", 7.8e9, "Fintech", true))
        l.add(RichPerson(484, "Zong Fuli", 7.8e9, "Beverages", true))
        l.add(RichPerson(485, "Tony Tamer", 7.8e9, "Private equity", true))
        l.add(RichPerson(486, "Sami Mnaymneh", 7.8e9, "Private equity", true))
        l.add(RichPerson(487, "Marc Benioff", 7.8e9, "Business software", true))
        l.add(RichPerson(488, "Stanley Druckenmiller", 7.8e9, "Hedge funds", true))
        l.add(RichPerson(489, "Rinat Akhmetov", 7.8e9, "Steel, coal", true))
        l.add(RichPerson(490, "Pang Kang", 7.8e9, "Soy sauce", true))
        l.add(RichPerson(491, "Wolfgang Marguerre & family", 7.7e9, "Pharmaceuticals", true))
        l.add(RichPerson(492, "Alain Bouchard", 7.7e9, "Convenience stores", true))
        l.add(RichPerson(493, "Jim Kavanaugh", 7.7e9, "IT provider", true))
        l.add(RichPerson(494, "Patrick Drahi", 7.7e9, "Telecom", true))
        l.add(RichPerson(495, "Dennis Washington", 7.7e9, "Construction, mining", true))
        l.add(RichPerson(496, "Mikhail Gutseriev", 7.7e9, "Oil, coal, real estate", true))
        l.add(RichPerson(497, "Zhang Daocai", 7.7e9, "Valves", true))
        l.add(RichPerson(498, "Koon Poh Keong", 7.6e9, "Aluminum", true))
        l.add(RichPerson(499, "Jeffrey Lurie", 7.6e9, "Philadelphia Eagles", true))
        l.add(RichPerson(500, "Marc Rowan", 7.6e9, "Private equity", true))
        l.add(RichPerson(501, "Karen Pritzker", 7.6e9, "Hotels, investments", true))
        l.add(RichPerson(502, "Daniel Nadler", 7.6e9, "AI software", true))
        l.add(RichPerson(503, "Hasmukh Chudgar & family", 7.6e9, "Pharmaceuticals", true))
        l.add(RichPerson(504, "Hao Tang", 7.6e9, "Advertising technology", true))
        l.add(RichPerson(505, "Vivek Chaand Sehgal", 7.6e9, "Auto parts", true))
        l.add(RichPerson(506, "Marian Ilitch & family", 7.6e9, "Little Caesars Pizza", true))
        l.add(RichPerson(507, "Maria Fernanda Amorim & family", 7.6e9, "Energy, investments", true))
        l.add(RichPerson(508, "Matthew Prince", 7.6e9, "Cybersecurity", true))
        l.add(RichPerson(509, "Melanie Perkins", 7.6e9, "Software", true))
        l.add(RichPerson(510, "Cliff Obrecht", 7.6e9, "Software", true))
        l.add(RichPerson(511, "Steven Rales", 7.5e9, "Manufacturing, investments", true))
        l.add(RichPerson(512, "Huang Xiaolei", 7.5e9, "Optical modules", true))
        l.add(RichPerson(513, "James Clark", 7.5e9, "Netscape, investments", true))
        l.add(RichPerson(514, "Xu Shihui", 7.5e9, "Snacks, beverages", true))
        l.add(RichPerson(515, "Jay Chaudhry", 7.5e9, "Security software", true))
        l.add(RichPerson(516, "Michael Kadoorie", 7.5e9, "Hotels, energy", true))
        l.add(RichPerson(517, "Satyanarayan Nuwal", 7.5e9, "Industrial explosives", true))
        l.add(RichPerson(518, "George Soros", 7.5e9, "Hedge funds", true))
        l.add(RichPerson(519, "Maria Angelicoussis", 7.5e9, "Shipping", true))
        l.add(RichPerson(520, "John Grayken", 7.5e9, "Private equity", true))
        l.add(RichPerson(521, "Brian Armstrong", 7.5e9, "Cryptocurrency", true))
        l.add(RichPerson(522, "Charles Simonyi", 7.5e9, "Microsoft", true))
        l.add(RichPerson(523, "Michael Milken", 7.5e9, "Investments", true))
        l.add(RichPerson(524, "Quek Leng Chan", 7.4e9, "Banking, property", true))
        l.add(RichPerson(525, "Dona Bertarelli", 7.4e9, "Biotech and investments", true))
        l.add(RichPerson(526, "Oleg Deripaska", 7.4e9, "Aluminum, utilities", true))
        l.add(RichPerson(527, "Juergen Blickle", 7.4e9, "Auto parts", true))
        l.add(RichPerson(528, "Min Kao & family", 7.4e9, "Navigation equipment", true))
        l.add(RichPerson(529, "Arkady Volozh", 7.4e9, "Search engine", true))
        l.add(RichPerson(530, "Li Ge", 7.4e9, "Pharmaceuticals", true))
        l.add(RichPerson(531, "Kerry Stokes", 7.3e9, "Construction equipment, media", true))
        l.add(RichPerson(532, "Janice McNair & family", 7.3e9, "Energy, sports", true))
        l.add(RichPerson(533, "Piero Ferrari & family", 7.3e9, "Automobiles", true))
        l.add(RichPerson(534, "Mark Walter", 7.3e9, "Finance, asset management", true))
        l.add(RichPerson(535, "Howard Lutnick & family", 7.3e9, "Finance", true))
        l.add(RichPerson(536, "Robin Li", 7.3e9, "Internet search", true))
        l.add(RichPerson(537, "Mat Ishbia", 7.3e9, "Mortgage lender", true))
        l.add(RichPerson(538, "Kjeld Kirk Kristiansen", 7.3e9, "Lego", true))
        l.add(RichPerson(539, "Frederik Paulsen", 7.2e9, "Health care", true))
        l.add(RichPerson(540, "Vincent Viola", 7.2e9, "Electronic trading", true))
        l.add(RichPerson(541, "Robert Ziff", 7.2e9, "Investments", true))
        l.add(RichPerson(542, "Daniel Ziff", 7.2e9, "Investments", true))
        l.add(RichPerson(543, "Dirk Ziff", 7.2e9, "Investments", true))
        l.add(RichPerson(544, "Abel Avellan", 7.1e9, "Telecoms", true))
        l.add(RichPerson(545, "Max Van Hoegaerden Herrmann Telles", 7.1e9, "Beer", true))
        l.add(RichPerson(546, "Albert Avdolyan", 7.1e9, "Oil, mining", true))
        l.add(RichPerson(547, "Otto Toto Sugiri", 7.1e9, "Data centers", true))
        l.add(RichPerson(548, "Daryl Katz", 7.1e9, "Pharmacies", true))
        l.add(RichPerson(549, "Ronda Stryker", 7.1e9, "Medical equipment", true))
        l.add(RichPerson(550, "Yang Shaopeng", 7.1e9, "Shipping", true))
        l.add(RichPerson(551, "Teddy Sagi", 7.1e9, "Gambling software", true))
        l.add(RichPerson(552, "Chase Coleman III", 7.1e9, "Investments", true))
        l.add(RichPerson(553, "Cui Genliang", 7.1e9, "Electric components", true))
        l.add(RichPerson(554, "Steven Spielberg", 7.1e9, "Movies", true))
        l.add(RichPerson(555, "Philip Ng", 7e9, "Real Estate", true))
        l.add(RichPerson(556, "Radovan Vitek", 7e9, "Real estate", true))
        l.add(RichPerson(557, "Edythe Broad & family", 7e9, "Homebuilding, insurance", true))
        l.add(RichPerson(558, "Patrick Ryan", 7e9, "Insurance", true))
        l.add(RichPerson(559, "Cho Jung-ho", 7e9, "Finance", true))
        l.add(RichPerson(560, "Evangelos Marinakis & family", 7e9, "Shipping, soccer", true))
        l.add(RichPerson(561, "Yang Chang-Chih", 7e9, "Printed circuit board", true))
        l.add(RichPerson(562, "Robert Ng", 6.9e9, "Real estate", true))
        l.add(RichPerson(563, "Florentino Perez", 6.9e9, "Construction", true))
        l.add(RichPerson(564, "Jeffrey Koo Jr", 6.9e9, "Finance", true))
        l.add(RichPerson(565, "Clive Calder", 6.9e9, "Record label", true))
        l.add(RichPerson(566, "Joe Lewis", 6.9e9, "Investments", true))
        l.add(RichPerson(567, "Li Hu & family", 6.9e9, "Memory and storage", true))
        l.add(RichPerson(568, "Stephen Smith", 6.9e9, "Finance and investments", true))
        l.add(RichPerson(569, "John Sall", 6.8e9, "Software", true))
        l.add(RichPerson(570, "Miguel Krigsner", 6.8e9, "Cosmetics", true))
        l.add(RichPerson(571, "Andrei Skoch & family", 6.8e9, "Metals and mining", true))
        l.add(RichPerson(572, "Rudolf Maag", 6.8e9, "Medical devices", true))
        l.add(RichPerson(573, "Euisun Chung", 6.8e9, "Hyundai", true))
        l.add(RichPerson(574, "John Brown", 6.8e9, "Medical equipment", true))
        l.add(RichPerson(575, "Horst Julius Pudwill", 6.8e9, "Manufacturing", true))
        l.add(RichPerson(576, "Ricardo Faria", 6.8e9, "Eggs", true))
        l.add(RichPerson(577, "Michael Otto", 6.8e9, "Retail, real estate", true))
        l.add(RichPerson(578, "Wang Xing", 6.8e9, "Food delivery", true))
        l.add(RichPerson(579, "Bruce Flatt", 6.8e9, "Money management", true))
        l.add(RichPerson(580, "Ronald Wanek", 6.7e9, "Furniture", true))
        l.add(RichPerson(581, "Herb Simon", 6.7e9, "Real estate", true))
        l.add(RichPerson(582, "Andrew Karam", 6.7e9, "Advertising technology", true))
        l.add(RichPerson(583, "Marcos Galperin", 6.7e9, "E-commerce", true))
        l.add(RichPerson(584, "Dmitry Rybolovlev & family", 6.7e9, "Fertilizer", true))
        l.add(RichPerson(585, "Paul Singer", 6.7e9, "Hedge funds", true))
        l.add(RichPerson(586, "Gary Rollins & family", 6.7e9, "Pest control", true))
        l.add(RichPerson(587, "Eren Ozmen", 6.7e9, "Aerospace", true))
        l.add(RichPerson(588, "Edward Roski Jr", 6.6e9, "Real estate", true))
        l.add(RichPerson(589, "Pavel Durov", 6.6e9, "Messaging app", true))
        l.add(RichPerson(590, "Ding Shizhong", 6.6e9, "Sports apparel", true))
        l.add(RichPerson(591, "Sumet Jiaravanon", 6.6e9, "Diversified", true))
        l.add(RichPerson(592, "Elizabeth Uihlein", 6.6e9, "Packaging materials", true))
        l.add(RichPerson(593, "Richard Uihlein", 6.6e9, "Packaging materials", true))
        l.add(RichPerson(594, "Martha Ingram & family", 6.6e9, "Book distribution, transportation", true))
        l.add(RichPerson(595, "Alexander Otto", 6.6e9, "Real estate", true))
        l.add(RichPerson(596, "Joseph Liemandt", 6.6e9, "Software", true))
        l.add(RichPerson(597, "Mike Adenuga", 6.6e9, "Telecom, oil", true))
        l.add(RichPerson(598, "Gao Guangrong", 6.6e9, "Optical modules", true))
        l.add(RichPerson(599, "Ray Lee Hunt", 6.6e9, "Oil, real estate", true))
        l.add(RichPerson(600, "Mohed Altrad", 6.6e9, "Scaffolding, cement mixers", true))
    }

    private fun c5(l: MutableList<RichPerson>) {
        l.add(RichPerson(601, "Mark Scheinberg", 6.6e9, "Online gambling", true))
        l.add(RichPerson(602, "Robert Rich Jr", 6.5e9, "Frozen foods", true))
        l.add(RichPerson(603, "Jaran Chiaravanont", 6.5e9, "Diversified", true))
        l.add(RichPerson(604, "Lu Weiding", 6.5e9, "Diversified", true))
        l.add(RichPerson(605, "Peter Gilgan", 6.5e9, "Homebuilding", true))
        l.add(RichPerson(606, "Hsieh Wen-Ta", 6.5e9, "Semiconductor testing equipment", true))
        l.add(RichPerson(607, "Peter Thomson", 6.5e9, "Thomson Reuters", true))
        l.add(RichPerson(608, "David Thomson", 6.5e9, "Thomson Reuters", true))
        l.add(RichPerson(609, "Taylor Thomson", 6.5e9, "Thomson Reuters", true))
        l.add(RichPerson(610, "Mathias Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(611, "Philipp Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(612, "Maximilian von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(613, "Erich von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(614, "Christian Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(615, "Christoph Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(616, "Hubertus von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(617, "Barbara Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(618, "Albert Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(619, "Ulrike von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(620, "Johannes von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(621, "Katharina von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(622, "Franz von Baumbach", 6.5e9, "Pharma", true))
        l.add(RichPerson(623, "Isabel Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(624, "Otto Boehringer", 6.5e9, "Pharmaceuticals", true))
        l.add(RichPerson(625, "Michael Intrator", 6.5e9, "Technology", true))
        l.add(RichPerson(626, "H. Ross Perot Jr", 6.5e9, "Real estate", true))
        l.add(RichPerson(627, "Carlos Alberto Sicupira & family", 6.5e9, "Beer", true))
        l.add(RichPerson(628, "Erich Wesjohann & family", 6.5e9, "Poultry genetics", true))
        l.add(RichPerson(629, "Tsai Eng-meng", 6.4e9, "Food, beverages", true))
        l.add(RichPerson(630, "Lee Thiam Wah", 6.4e9, "Retailing", true))
        l.add(RichPerson(631, "Fatih Ozmen", 6.4e9, "Aerospace", true))
        l.add(RichPerson(632, "Seo Jung-jin", 6.4e9, "Biotech", true))
        l.add(RichPerson(633, "Jim Davis & family", 6.4e9, "New Balance", true))
        l.add(RichPerson(634, "Dietmar Hopp & family", 6.4e9, "Software", true))
        l.add(RichPerson(635, "Timur Turlov", 6.4e9, "Stock brokerage", true))
        l.add(RichPerson(636, "Stefan Reimann-Andersen", 6.4e9, "Consumer goods", true))
        l.add(RichPerson(637, "Wolfgang Reimann", 6.4e9, "Consumer goods", true))
        l.add(RichPerson(638, "Renate Reimann-Haas", 6.4e9, "Consumer goods", true))
        l.add(RichPerson(639, "Matthias Reimann-Andersen", 6.4e9, "Consumer goods", true))
        l.add(RichPerson(640, "Rahul Bhatia", 6.3e9, "Aviation", true))
        l.add(RichPerson(641, "Remon Vos", 6.3e9, "Logistics real estate", true))
        l.add(RichPerson(642, "Arnon Milchan", 6.3e9, "Movie making", true))
        l.add(RichPerson(643, "Andrew Cherng", 6.3e9, "Fast food", true))
        l.add(RichPerson(644, "Peggy Cherng", 6.3e9, "Fast food", true))
        l.add(RichPerson(645, "Ding Shijia", 6.3e9, "Sports apparel", true))
        l.add(RichPerson(646, "Stefano Pessina", 6.3e9, "Drugstores", true))
        l.add(RichPerson(647, "Zhang Congyuan", 6.3e9, "Shoes", true))
        l.add(RichPerson(648, "Jayshree Ullal", 6.3e9, "Computer networking", true))
        l.add(RichPerson(649, "Clifford Asness", 6.3e9, "Money management", true))
        l.add(RichPerson(650, "Steve Lavin & family", 6.3e9, "Meat processing", true))
        l.add(RichPerson(651, "Gopikishan Damani", 6.3e9, "Retail, investments", true))
        l.add(RichPerson(652, "Franz Viegener", 6.2e9, "Plumbing/HVAC", true))
        l.add(RichPerson(653, "Thomas Kaeser", 6.2e9, "Air systems", true))
        l.add(RichPerson(654, "Robert Bass", 6.2e9, "Oil, investments", true))
        l.add(RichPerson(655, "Mark Meijer & family", 6.2e9, "Supermarkets", true))
        l.add(RichPerson(656, "Doug Meijer & family", 6.2e9, "Supermarkets", true))
        l.add(RichPerson(657, "Hank Meijer & family", 6.2e9, "Supermarkets", true))
        l.add(RichPerson(658, "Stefan von Holtzbrinck", 6.2e9, "Publishing", true))
        l.add(RichPerson(659, "Christiane Schoeller", 6.2e9, "Publishing", true))
        l.add(RichPerson(660, "Anna Viegener", 6.2e9, "Plumbing/HVAC", true))
        l.add(RichPerson(661, "Emanuele (Lino) Saputo & family", 6.2e9, "Cheese", true))
        l.add(RichPerson(662, "Xu Gaoming", 6.2e9, "Gold and jewelry", true))
        l.add(RichPerson(663, "Jean (Gigi) Pritzker", 6.2e9, "Hotels, investments", true))
        l.add(RichPerson(664, "Xu Hang", 6.1e9, "Medical devices", true))
        l.add(RichPerson(665, "Liu Hanyuan", 6.1e9, "Agribusiness, new energy", true))
        l.add(RichPerson(666, "Jack Dorsey", 6.1e9, "Twitter, Square", true))
        l.add(RichPerson(667, "Donald Trump", 6.1e9, "Real estate", true))
        l.add(RichPerson(668, "Charles B. Johnson", 6.1e9, "Franklin Templeton", true))
        l.add(RichPerson(669, "Mitchell Morgan & family", 6.1e9, "Real estate", true))
        l.add(RichPerson(670, "Gwendolyn Sontheim Meyer", 6.1e9, "Cargill", true))
        l.add(RichPerson(671, "Tse Ping & family", 6.1e9, "Pharmaceuticals", true))
        l.add(RichPerson(672, "Bill Haslam", 6e9, "Gas stations", true))
        l.add(RichPerson(673, "Robert Hale Jr", 6e9, "Telecom", true))
        l.add(RichPerson(674, "Mark Cuban", 6e9, "Online media, Dallas Mavericks", true))
        l.add(RichPerson(675, "James Chambers", 6e9, "Media, automotive", true))
        l.add(RichPerson(676, "Margaretta Taylor", 6e9, "Media, automotive", true))
        l.add(RichPerson(677, "Katharine Rayner", 6e9, "Media, automotive", true))
        l.add(RichPerson(678, "Mikhail Lomtadze", 6e9, "Fintech", true))
        l.add(RichPerson(679, "Cai Haoyu", 6e9, "Mobile games", true))
        l.add(RichPerson(680, "William Goldring & family", 6e9, "Liquor", true))
        l.add(RichPerson(681, "Andrew Currie", 6e9, "Chemicals", true))
        l.add(RichPerson(682, "Xu Sky", 6e9, "E-commerce", true))
        l.add(RichPerson(683, "William Berkley & family", 6e9, "Insurance", true))
        l.add(RichPerson(684, "John Reece", 6e9, "Chemicals", true))
        l.add(RichPerson(685, "Shari Arison", 6e9, "Carnival Cruises", true))
        l.add(RichPerson(686, "Liu Sheng", 6e9, "Optical communication", true))
        l.add(RichPerson(687, "Vladimir Kim", 5.9e9, "Mining", true))
        l.add(RichPerson(688, "Jorge Moll Filho & family", 5.9e9, "Hospitals", true))
        l.add(RichPerson(689, "Rick Caruso", 5.9e9, "Real estate", true))
        l.add(RichPerson(690, "Michael Novogratz", 5.9e9, "Investments, cryptocurrency", true))
        l.add(RichPerson(691, "Trevor Rees-Jones", 5.9e9, "Oil & gas", true))
        l.add(RichPerson(692, "Richard Li", 5.9e9, "Insurance, telecom", true))
        l.add(RichPerson(693, "Alain Merieux & family", 5.9e9, "Pharmaceuticals", true))
        l.add(RichPerson(694, "Michael Ashley", 5.9e9, "Sports retailing", true))
        l.add(RichPerson(695, "Ma Jianrong", 5.9e9, "Textiles, apparel", true))
        l.add(RichPerson(696, "Lutz Mario Helmig & family", 5.9e9, "Hospitals", true))
        l.add(RichPerson(697, "Alexander Abramov", 5.8e9, "Steel, mining", true))
        l.add(RichPerson(698, "Don Vultaggio & family", 5.8e9, "Beverages", true))
        l.add(RichPerson(699, "Benu Gopal Bangur", 5.8e9, "Cement", true))
        l.add(RichPerson(700, "Lin Shu-hong", 5.8e9, "Petrochemicals", true))
        l.add(RichPerson(701, "Mario Verrocchi", 5.8e9, "Pharmacies", true))
        l.add(RichPerson(702, "Tom Morris", 5.8e9, "Retail", true))
        l.add(RichPerson(703, "Annette Lerner & family", 5.8e9, "Real estate", true))
        l.add(RichPerson(704, "Giuseppe De'Longhi & family", 5.8e9, "Coffee makers", true))
        l.add(RichPerson(705, "Leonardo Maria Del Vecchio", 5.8e9, "Eyeglasses", true))
        l.add(RichPerson(706, "Alex Behring", 5.8e9, "Investments", true))
        l.add(RichPerson(707, "Wu Yajun", 5.8e9, "Real estate", true))
        l.add(RichPerson(708, "John A. Sobrato & family", 5.8e9, "Real estate", true))
        l.add(RichPerson(709, "Margot Birmingham Perot", 5.8e9, "Computer services, real estate", true))
        l.add(RichPerson(710, "Peter Kellogg", 5.8e9, "Investments", true))
        l.add(RichPerson(711, "Yasumitsu Shigeta", 5.8e9, "Mobile phone retailer", true))
        l.add(RichPerson(712, "Michal Solowow", 5.8e9, "Investments", true))
        l.add(RichPerson(713, "Wolfgang Herz", 5.8e9, "Coffee", true))
        l.add(RichPerson(714, "Michael Herz", 5.8e9, "Coffee", true))
        l.add(RichPerson(715, "Patrizio Vinciarelli", 5.7e9, "Electronic components", true))
        l.add(RichPerson(716, "Thomas Secunda", 5.7e9, "Bloomberg LP", true))
        l.add(RichPerson(717, "Richard Liu", 5.7e9, "E-commerce", true))
        l.add(RichPerson(718, "John Henry", 5.7e9, "Sports", true))
        l.add(RichPerson(719, "Andre Koo", 5.7e9, "Financial services", true))
        l.add(RichPerson(720, "Tomas Olivo Lopez", 5.7e9, "Shopping centers", true))
    }

    private fun c6(l: MutableList<RichPerson>) {
        l.add(RichPerson(721, "Carl Thoma", 5.7e9, "Private equity", true))
        l.add(RichPerson(722, "Carl Douglas", 5.7e9, "Investments", true))
        l.add(RichPerson(723, "Chen Weiliang", 5.7e9, "Semiconductors", true))
        l.add(RichPerson(724, "Eric Yuan & family", 5.6e9, "Zoom Video Communications", true))
        l.add(RichPerson(725, "Claudio Del Vecchio", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(726, "Marisa Del Vecchio", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(727, "Rocco Basilico", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(728, "Nicoletta Zampillo", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(729, "Luca Del Vecchio", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(730, "Paola Del Vecchio", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(731, "Clemente Del Vecchio", 5.6e9, "Eyeglasses", true))
        l.add(RichPerson(732, "Michel Leclercq & family", 5.6e9, "Sporting goods", true))
        l.add(RichPerson(733, "Edward Stack & family", 5.6e9, "Dick's Sporting Goods", true))
        l.add(RichPerson(734, "Heinrich Otto Deichmann", 5.6e9, "Shoes, retail", true))
        l.add(RichPerson(735, "Alejandro Bulgheroni", 5.6e9, "Oil & gas", true))
        l.add(RichPerson(736, "Renuka Jagtiani", 5.6e9, "Retail", true))
        l.add(RichPerson(737, "Naguib Sawiris", 5.6e9, "Telecom", true))
        l.add(RichPerson(738, "Archie Aldis Emmerson & family", 5.6e9, "Timberland, lumber mills", true))
        l.add(RichPerson(739, "Bob Gaglardi & family", 5.6e9, "Hotels", true))
        l.add(RichPerson(740, "Liu Yonghao & family", 5.6e9, "Agribusiness", true))
        l.add(RichPerson(741, "Chen Bang", 5.6e9, "Hospitals", true))
        l.add(RichPerson(742, "Ali Ghodsi", 5.5e9, "Data analytics", true))
        l.add(RichPerson(743, "Romesh T. Wadhwani", 5.5e9, "Software", true))
        l.add(RichPerson(744, "M.A. Yusuff Ali", 5.5e9, "Retail", true))
        l.add(RichPerson(745, "Margarita Louis-Dreyfus & family", 5.5e9, "Commodities", true))
        l.add(RichPerson(746, "Marianne Liebmann", 5.5e9, "Cargill", true))
        l.add(RichPerson(747, "James Cargill II", 5.5e9, "Cargill", true))
        l.add(RichPerson(748, "Austen Cargill II", 5.5e9, "Cargill", true))
        l.add(RichPerson(749, "Neal Blue & family", 5.5e9, "Defense", true))
        l.add(RichPerson(750, "Jeff Skoll", 5.5e9, "EBay", true))
        l.add(RichPerson(751, "Cho Jyh-jer", 5.5e9, "Semiconductors", true))
        l.add(RichPerson(752, "Gordon Getty & family", 5.5e9, "Getty Oil", true))
        l.add(RichPerson(753, "Jiang Bin", 5.5e9, "Acoustic components", true))
        l.add(RichPerson(754, "Justin Ishbia", 5.5e9, "Private equity", true))
        l.add(RichPerson(755, "Gao Dekang & family", 5.5e9, "Apparel", true))
        l.add(RichPerson(756, "Maria Del Pino", 5.5e9, "Construction", true))
        l.add(RichPerson(757, "Eric Douglas", 5.5e9, "Investments", true))
        l.add(RichPerson(758, "Chip Wilson", 5.5e9, "Lululemon", true))
        l.add(RichPerson(759, "Forrest Li", 5.4e9, "Online gaming, e-commerce", true))
        l.add(RichPerson(760, "Jon Yarbrough", 5.4e9, "Gambling machines", true))
        l.add(RichPerson(761, "Jeremy Jacobs Sr & family", 5.4e9, "Food service", true))
        l.add(RichPerson(762, "Shapoor Mistry", 5.4e9, "Diversified", true))
        l.add(RichPerson(763, "Jerzy Starak", 5.4e9, "Pharmaceuticals", true))
        l.add(RichPerson(764, "Russell Savage", 5.4e9, "Energy drinks", true))
        l.add(RichPerson(765, "Zhu Baoguo & family", 5.4e9, "Pharmaceuticals", true))
        l.add(RichPerson(766, "Bulat Utemuratov", 5.4e9, "Mining, banking, hotels", true))
        l.add(RichPerson(767, "Stewart Resnick", 5.4e9, "Agriculture", true))
        l.add(RichPerson(768, "Lynda Resnick", 5.4e9, "Agriculture", true))
        l.add(RichPerson(769, "Rakesh Gangwal", 5.4e9, "Airline", true))
        l.add(RichPerson(770, "Ivan Tavrin", 5.4e9, "Private equity", true))
        l.add(RichPerson(771, "Peter Spuhler", 5.4e9, "Train cars", true))
        l.add(RichPerson(772, "Torbjorn Tornqvist", 5.4e9, "Oil trading", true))
        l.add(RichPerson(773, "Fan Hongwei", 5.4e9, "Petrochemicals", true))
        l.add(RichPerson(774, "George Economou", 5.3e9, "Shipping", true))
        l.add(RichPerson(775, "Thomas Tull", 5.3e9, "Movies, investments", true))
        l.add(RichPerson(776, "Mangal Prabhat Lodha", 5.3e9, "Real estate", true))
        l.add(RichPerson(777, "Peter Beck", 5.3e9, "Spacecrafts", true))
        l.add(RichPerson(778, "Arkady Rotenberg", 5.3e9, "Construction, pipes, banking", true))
        l.add(RichPerson(779, "Matthias Reinhart", 5.3e9, "Financial services", true))
        l.add(RichPerson(780, "Ian Livingstone", 5.3e9, "Real estate", true))
        l.add(RichPerson(781, "Richard Livingstone", 5.3e9, "Real estate", true))
        l.add(RichPerson(782, "Dinara Kulibayeva", 5.3e9, "Banking", true))
        l.add(RichPerson(783, "Timur Kulibayev", 5.3e9, "Banking", true))
        l.add(RichPerson(784, "Hu Baifan", 5.3e9, "Pharmaceuticals", true))
        l.add(RichPerson(785, "Lai Meisong", 5.2e9, "Package delivery", true))
        l.add(RichPerson(786, "Gail Miller & family", 5.2e9, "Car dealerships", true))
        l.add(RichPerson(787, "Josh Kushner", 5.2e9, "Venture capital", true))
        l.add(RichPerson(788, "Andrei Kozitsyn", 5.2e9, "Metals", true))
        l.add(RichPerson(789, "Murat Ulker", 5.2e9, "Food", true))
        l.add(RichPerson(790, "Shaul Shani", 5.2e9, "Telecom", true))
        l.add(RichPerson(791, "Sofia Hogberg Schorling", 5.2e9, "Investments", true))
        l.add(RichPerson(792, "Isaac Perlmutter", 5.2e9, "Marvel comics", true))
        l.add(RichPerson(793, "Rupert Johnson Jr", 5.2e9, "Franklin Templeton", true))
        l.add(RichPerson(794, "Reinhold Schmieding", 5.2e9, "Medical devices", true))
        l.add(RichPerson(795, "Zhang Yong", 5.2e9, "Restaurants", true))
        l.add(RichPerson(796, "Marta Schorling Andreen", 5.1e9, "Investments", true))
        l.add(RichPerson(797, "Willy Michel", 5.1e9, "Medical devices", true))
        l.add(RichPerson(798, "Kailashchandra Nuwal", 5.1e9, "Industrial explosives", true))
        l.add(RichPerson(799, "Tom Golisano", 5.1e9, "Payroll services", true))
        l.add(RichPerson(800, "Venu Srinivasan", 5.1e9, "Two-wheelers", true))
        l.add(RichPerson(801, "Lorinc Meszaros", 5.1e9, "Diversified", true))
        l.add(RichPerson(802, "Kwak Dong Shin", 5.1e9, "Semiconductors", true))
        l.add(RichPerson(803, "Gaye Farncombe", 5.1e9, "Thomson Reuters", true))
        l.add(RichPerson(804, "Linda Campbell", 5.1e9, "Thomson Reuters", true))
        l.add(RichPerson(805, "God Nisanov", 5.1e9, "Real estate", true))
        l.add(RichPerson(806, "Zarakh Iliev", 5.1e9, "Real estate", true))
        l.add(RichPerson(807, "Cen Junda", 5.1e9, "Pharmaceuticals", true))
        l.add(RichPerson(808, "Rajiv Bajaj", 5.1e9, "Diversified", true))
        l.add(RichPerson(809, "Sanjiv Bajaj", 5.1e9, "Diversified", true))
        l.add(RichPerson(810, "George Lucas", 5.1e9, "Star Wars", true))
        l.add(RichPerson(811, "Jamshyd Godrej", 5.1e9, "Consumer goods, real estate", true))
        l.add(RichPerson(812, "Smita Crishna Godrej", 5.1e9, "Consumer goods", true))
        l.add(RichPerson(813, "Pyotr Aven", 5.1e9, "Oil, banking, telecom", true))
        l.add(RichPerson(814, "Jorge Mas", 5.1e9, "Construction", true))
        l.add(RichPerson(815, "Joao Moreira Salles", 5.1e9, "Banking, minerals", true))
        l.add(RichPerson(816, "Walther Moreira Salles Junior", 5.1e9, "Banking, minerals", true))
        l.add(RichPerson(817, "Tim Sweeney", 5.1e9, "Video games", true))
        l.add(RichPerson(818, "Frank Wang", 5.1e9, "Drones", true))
        l.add(RichPerson(819, "Georg Nemetschek & family", 5.1e9, "Software", true))
        l.add(RichPerson(820, "Andy Mills", 5.1e9, "Medical supplies", true))
        l.add(RichPerson(821, "Zhang Hongfu", 5.1e9, "Bubble tea", true))
        l.add(RichPerson(822, "Zhang Hongchao", 5.1e9, "Bubble tea", true))
        l.add(RichPerson(823, "Jeffrey Cheah", 5.1e9, "Property, healthcare", true))
        l.add(RichPerson(824, "Marina Budiman", 5.1e9, "Data centers", true))
        l.add(RichPerson(825, "Thomas Straumann", 5e9, "Dental implants", true))
        l.add(RichPerson(826, "Robert Faith", 5e9, "Real estate management", true))
        l.add(RichPerson(827, "Chandru Raheja", 5e9, "Real estate", true))
        l.add(RichPerson(828, "Matei Zaharia", 5e9, "Data analytics", true))
        l.add(RichPerson(829, "Ion Stoica", 5e9, "Data analytics", true))
        l.add(RichPerson(830, "Fernand Huts", 5e9, "Logistics, transportation", true))
        l.add(RichPerson(831, "Vlad Tenev", 5e9, "Stock trading app", true))
        l.add(RichPerson(832, "Joy Alukkas", 5e9, "Jewelry", true))
        l.add(RichPerson(833, "Hortensia Herrero", 5e9, "Supermarkets", true))
        l.add(RichPerson(834, "Arturo Moreno", 5e9, "Billboards, Los Angeles Angels", true))
        l.add(RichPerson(835, "Ryan Cohen", 5e9, "Investments", true))
        l.add(RichPerson(836, "Huang Li", 5e9, "Imaging systems", true))
        l.add(RichPerson(837, "Palmer Luckey", 5e9, "Virtual reality, defense technology", true))
        l.add(RichPerson(838, "Xiao Yongming & family", 5e9, "Fertilizer", true))
        l.add(RichPerson(839, "Anthony von Mandl", 5e9, "Alcoholic beverages", true))
        l.add(RichPerson(840, "Stephen Feinberg", 5e9, "Private equity", true))
    }

    private fun c7(l: MutableList<RichPerson>) {
        l.add(RichPerson(841, "Ruan Xueping", 5e9, "Power strip", true))
        l.add(RichPerson(842, "Shen Guojun", 5e9, "Retail", true))
        l.add(RichPerson(843, "Mike Brown & family", 5e9, "Cincinnati Bengals", true))
        l.add(RichPerson(844, "Saban Cemil Kazanci", 5e9, "Energy", true))
        l.add(RichPerson(845, "Stephen Mandel Jr", 5e9, "Hedge funds", true))
        l.add(RichPerson(846, "Hu Haiyang", 4.9e9, "Optical and semiconductor testing equipment", true))
        l.add(RichPerson(847, "Zhu Yan & family", 4.9e9, "Real estate", true))
        l.add(RichPerson(848, "Peter Cancro", 4.9e9, "Jersey Mike's Subs", true))
        l.add(RichPerson(849, "Nusli Wadia", 4.9e9, "Consumer goods", true))
        l.add(RichPerson(850, "Ruan Liping", 4.9e9, "Power strips", true))
        l.add(RichPerson(851, "Jon Stryker", 4.9e9, "Medical equipment", true))
        l.add(RichPerson(852, "Igor Altushkin", 4.9e9, "Metals", true))
        l.add(RichPerson(853, "Barry Diller", 4.9e9, "Online media", true))
        l.add(RichPerson(854, "Stephen Cohen", 4.9e9, "Software", true))
        l.add(RichPerson(855, "Anthony Pritzker", 4.9e9, "Hotels, investments", true))
        l.add(RichPerson(856, "Scott Crabill", 4.9e9, "Private equity", true))
        l.add(RichPerson(857, "Holden Spaht", 4.9e9, "Private equity", true))
        l.add(RichPerson(858, "Martin Haefner", 4.9e9, "Software, investments", true))
        l.add(RichPerson(859, "Steven Klinsky", 4.9e9, "Investments", true))
        l.add(RichPerson(860, "Ronald Lauder", 4.9e9, "Estee Lauder", true))
        l.add(RichPerson(861, "Baiju Bhatt", 4.9e9, "Stock trading app", true))
        l.add(RichPerson(862, "Dan Kurzius", 4.9e9, "Email marketing", true))
        l.add(RichPerson(863, "Seth Boro", 4.9e9, "Private equity", true))
        l.add(RichPerson(864, "Maria-Elisabeth Schaeffler-Thumann", 4.9e9, "Auto parts", true))
        l.add(RichPerson(865, "Lachhman Das Mittal", 4.9e9, "Tractors", true))
        l.add(RichPerson(866, "Joseph Grendys", 4.9e9, "Poultry processing", true))
        l.add(RichPerson(867, "Andrei Bokarev", 4.9e9, "Metals, mining", true))
        l.add(RichPerson(868, "Bert Beveridge", 4.8e9, "Vodka", true))
        l.add(RichPerson(869, "Joe Mansueto", 4.8e9, "Investment research", true))
        l.add(RichPerson(870, "N. Murray Edwards", 4.8e9, "Oil & gas", true))
        l.add(RichPerson(871, "John Catsimatidis", 4.8e9, "Oil, real estate", true))
        l.add(RichPerson(872, "Liu Jincheng & family", 4.8e9, "Lithium batteries", true))
        l.add(RichPerson(873, "Penny Pritzker", 4.8e9, "Hotels, investments", true))
        l.add(RichPerson(874, "Pablo Legorreta", 4.8e9, "Investments", true))
        l.add(RichPerson(875, "Igor Kesaev", 4.8e9, "Tobacco distribution, retail", true))
        l.add(RichPerson(876, "Garrett Camp", 4.8e9, "Uber", true))
        l.add(RichPerson(877, "Alexis Le-Quoc", 4.8e9, "Cloud computing", true))
        l.add(RichPerson(878, "Baba Kalyani", 4.8e9, "Engineering", true))
        l.add(RichPerson(879, "Xu Jinfu & family", 4.8e9, "Chemicals", true))
        l.add(RichPerson(880, "Lin Lairong & family", 4.8e9, "Iron ore mining", true))
        l.add(RichPerson(881, "Henning Oldendorff", 4.8e9, "Shipping", true))
        l.add(RichPerson(882, "Li Hua", 4.8e9, "Financial services", true))
        l.add(RichPerson(883, "Nithin Kamath", 4.7e9, "Financial services", true))
        l.add(RichPerson(884, "Lee Yeow Chor", 4.7e9, "Palm oil, property", true))
        l.add(RichPerson(885, "Hamad bin Jassim bin Jaber Al Thani", 4.7e9, "Investments", true))
        l.add(RichPerson(886, "Hansjoerg Wyss", 4.7e9, "Medical devices", true))
        l.add(RichPerson(887, "Vikas Oberoi", 4.7e9, "Real estate", true))
        l.add(RichPerson(888, "Dan Snyder", 4.7e9, "Washington Commanders", true))
        l.add(RichPerson(889, "Cho Tak Wong", 4.7e9, "Auto parts", true))
        l.add(RichPerson(890, "Nicolas D'Ieteren", 4.7e9, "Auto parts, distribution", true))
        l.add(RichPerson(891, "Eric Lefkofsky", 4.7e9, "Groupon, investments", true))
        l.add(RichPerson(892, "Egor Kulkov", 4.7e9, "Pharmaceuticals", true))
        l.add(RichPerson(893, "George Bishop", 4.7e9, "Oil & gas", true))
        l.add(RichPerson(894, "Reed Hastings", 4.7e9, "Netflix", true))
        l.add(RichPerson(895, "Hans Peter Wild", 4.7e9, "Flavorings", true))
        l.add(RichPerson(896, "Yan Junjie", 4.7e9, "AI", true))
        l.add(RichPerson(897, "Chey Tae-won", 4.7e9, "Oil, semiconductor", true))
        l.add(RichPerson(898, "George Prokopiou & family", 4.7e9, "Shipping", true))
        l.add(RichPerson(899, "Walter Frey", 4.7e9, "Car dealerships", true))
        l.add(RichPerson(900, "Abdulla Al Futtaim & family", 4.7e9, "Auto dealers, investments", true))
        l.add(RichPerson(901, "Qiu Jianping & family", 4.6e9, "Hand tools", true))
        l.add(RichPerson(902, "Erwin Franz Mueller", 4.6e9, "Drugstores", true))
        l.add(RichPerson(903, "Beatriz Davila de Santo Domingo", 4.6e9, "Beer", true))
        l.add(RichPerson(904, "Angelo Koo", 4.6e9, "Finance", true))
        l.add(RichPerson(905, "Daniel D'Aniello", 4.6e9, "Private equity", true))
        l.add(RichPerson(906, "Steven Udvar-Hazy", 4.6e9, "Aircraft leasing", true))
        l.add(RichPerson(907, "Scott Cook", 4.6e9, "Software", true))
        l.add(RichPerson(908, "Catherine Commisso & family", 4.6e9, "Telecom", true))
        l.add(RichPerson(909, "Sergio Stevanato & family", 4.6e9, "Medical packaging", true))
        l.add(RichPerson(910, "Zhang Jianzhong", 4.6e9, "Semiconductor", true))
        l.add(RichPerson(911, "Nikolai Buinov", 4.6e9, "Oil, gas", true))
        l.add(RichPerson(912, "Xiao Hongxing", 4.6e9, "Manufacturing", true))
        l.add(RichPerson(913, "Scott Kapnick", 4.6e9, "Private equity", true))
        l.add(RichPerson(914, "Jiang Weiping & family", 4.6e9, "Chemicals", true))
        l.add(RichPerson(915, "Abdulla bin Ahmad Al Ghurair & family", 4.6e9, "Diversified", true))
        l.add(RichPerson(916, "David Filo", 4.6e9, "Yahoo", true))
        l.add(RichPerson(917, "Eleanor Butt Crook & family", 4.6e9, "Supermarkets", true))
        l.add(RichPerson(918, "Paul Foster", 4.6e9, "Oil refining", true))
        l.add(RichPerson(919, "Takao Yasuda", 4.5e9, "Retail", true))
        l.add(RichPerson(920, "Thomas Hagen & family", 4.5e9, "Insurance", true))
        l.add(RichPerson(921, "Drayton McLane Jr", 4.5e9, "Walmart, logistics", true))
        l.add(RichPerson(922, "Michael Pieper", 4.5e9, "Kitchen appliances", true))
        l.add(RichPerson(923, "Eduardo Hochschild", 4.5e9, "Mining", true))
        l.add(RichPerson(924, "Marc Ladreit de Lacharriere", 4.5e9, "Finance", true))
        l.add(RichPerson(925, "Helen Johnson-Leipold", 4.5e9, "Cleaning products", true))
        l.add(RichPerson(926, "Laurence Graff & family", 4.5e9, "Diamond jewelry", true))
        l.add(RichPerson(927, "Han Tao", 4.5e9, "Electronics components", true))
        l.add(RichPerson(928, "Aristotelis Mistakidis", 4.5e9, "Mining, commodities", true))
        l.add(RichPerson(929, "Liang Zhaoxian", 4.5e9, "Appliances", true))
        l.add(RichPerson(930, "Li Chunan", 4.5e9, "Solar wafers and modules", true))
        l.add(RichPerson(931, "John Gandel", 4.5e9, "Shopping malls", true))
        l.add(RichPerson(932, "Mahendra Choksi & family", 4.5e9, "Paints", true))
        l.add(RichPerson(933, "Friede Springer", 4.5e9, "Publishing", true))
        l.add(RichPerson(934, "James Duff", 4.5e9, "Tires, diversified", true))
        l.add(RichPerson(935, "Herbert Wertheim", 4.5e9, "Investments", true))
        l.add(RichPerson(936, "Julia Thiele-Schuerhoff & family", 4.5e9, "Brakes, investments", true))
        l.add(RichPerson(937, "Thomas Duff", 4.5e9, "Tires, diversified", true))
        l.add(RichPerson(938, "Fabien Pinckaers", 4.5e9, "Software", true))
        l.add(RichPerson(939, "Lynn Schusterman & family", 4.4e9, "Oil & gas, investments", true))
        l.add(RichPerson(940, "Danielle Bellon & family", 4.4e9, "Food services", true))
        l.add(RichPerson(941, "Abhay Firodia", 4.4e9, "Automobiles", true))
        l.add(RichPerson(942, "Jose Roberto Marinho", 4.4e9, "Media", true))
        l.add(RichPerson(943, "Lee Yeow Seng", 4.4e9, "Palm oil, property", true))
        l.add(RichPerson(944, "Joao Roberto Marinho", 4.4e9, "Media", true))
        l.add(RichPerson(945, "Sun Weijie", 4.4e9, "Oilfield equipment", true))
        l.add(RichPerson(946, "Winifred J. Marquart", 4.4e9, "Cleaning products", true))
        l.add(RichPerson(947, "Anna Katharina Viessmann", 4.4e9, "Heating and cooling equipment", true))
        l.add(RichPerson(948, "Andreas Martinos & family", 4.4e9, "Shipping", true))
        l.add(RichPerson(949, "Carlo Fidani", 4.4e9, "Real estate", true))
        l.add(RichPerson(950, "H. Fisk Johnson", 4.4e9, "Cleaning products", true))
        l.add(RichPerson(951, "S. Curtis Johnson", 4.4e9, "Cleaning products", true))
        l.add(RichPerson(952, "Dagmar Dolby & family", 4.4e9, "Dolby Laboratories", true))
        l.add(RichPerson(953, "Miao Hangen", 4.4e9, "Textiles, petrochemicals", true))
        l.add(RichPerson(954, "Tang Jie", 4.4e9, "Artificial intelligence", true))
        l.add(RichPerson(955, "Cui Lixin", 4.4e9, "Aluminum", true))
        l.add(RichPerson(956, "Lin Chen-hai", 4.4e9, "Real estate", true))
        l.add(RichPerson(957, "Jiang Rensheng & family", 4.4e9, "Vaccines", true))
        l.add(RichPerson(958, "Eduardo Eurnekian", 4.4e9, "Airports, investments", true))
        l.add(RichPerson(959, "Donald Sterling", 4.4e9, "Real estate", true))
        l.add(RichPerson(960, "Ben Chestnut", 4.4e9, "Email marketing", true))
    }

    private fun c8(l: MutableList<RichPerson>) {
        l.add(RichPerson(961, "Richard Schulze", 4.4e9, "Best Buy", true))
        l.add(RichPerson(962, "Wang Jianlin", 4.3e9, "Real estate", true))
        l.add(RichPerson(963, "Angela Bennett", 4.3e9, "Mining", true))
        l.add(RichPerson(964, "Carlos Hank Rhon & family", 4.3e9, "Banking", true))
        l.add(RichPerson(965, "Phil Ruffin", 4.3e9, "Casinos, real estate", true))
        l.add(RichPerson(966, "Byron Trott", 4.3e9, "Investments", true))
        l.add(RichPerson(967, "Feridun Gecgel", 4.3e9, "Utility Equipment", true))
        l.add(RichPerson(968, "Wendy Abrams", 4.3e9, "Medical supplies", true))
        l.add(RichPerson(969, "Alexandre Van Damme", 4.3e9, "ABInBev", true))
        l.add(RichPerson(970, "Roberto Crippa", 4.3e9, "Microchip testing", true))
        l.add(RichPerson(971, "Cristiano Crippa", 4.3e9, "Microchip testing", true))
        l.add(RichPerson(972, "John Middleton", 4.3e9, "Tobacco", true))
        l.add(RichPerson(973, "Eduardo Vivas", 4.3e9, "Advertising technology", true))
        l.add(RichPerson(974, "Maggie Hardy", 4.3e9, "Building materials", true))
        l.add(RichPerson(975, "C. Dean Metropoulos", 4.3e9, "Investments", true))
        l.add(RichPerson(976, "J.B. Pritzker", 4.3e9, "Hotels, investments", true))
        l.add(RichPerson(977, "Markus Blocher", 4.3e9, "Chemicals", true))
        l.add(RichPerson(978, "Bernard Fraisse & family", 4.3e9, "Pharmaceuticals", true))
        l.add(RichPerson(979, "Li Min", 4.3e9, "Semiconductor", true))
        l.add(RichPerson(980, "Pansy Ho", 4.3e9, "Casinos", true))
        l.add(RichPerson(981, "Hamilton James & family", 4.3e9, "Investments", true))
        l.add(RichPerson(982, "Yeung Kin-man", 4.3e9, "Electronics", true))
        l.add(RichPerson(983, "Somurai Jaruphnit", 4.3e9, "Diversified", true))
        l.add(RichPerson(984, "Stewart Rahr", 4.3e9, "Drug distribution", true))
        l.add(RichPerson(985, "Michael Jordan", 4.3e9, "Charlotte Hornets, endorsements", true))
        l.add(RichPerson(986, "Andrej Babis", 4.3e9, "Agriculture", true))
        l.add(RichPerson(987, "Antonio Gracias", 4.3e9, "Investments", true))
        l.add(RichPerson(988, "Sid Bass", 4.3e9, "Oil, investments", true))
        l.add(RichPerson(989, "Ravi Pillai", 4.3e9, "Construction", true))
        l.add(RichPerson(990, "Yu Renrong", 4.3e9, "Semiconductors", true))
        l.add(RichPerson(991, "Renzo Rosso & family", 4.3e9, "Fashion", true))
        l.add(RichPerson(992, "Xia Zuoquan", 4.2e9, "Automobiles, batteries", true))
        l.add(RichPerson(993, "Kevin David Lehmann", 4.2e9, "Drugstores", true))
        l.add(RichPerson(994, "Miguel Fluxa Rossello", 4.2e9, "Hotels", true))
        l.add(RichPerson(995, "Cai Kui", 4.2e9, "Real estate", true))
        l.add(RichPerson(996, "Anne Beaufour", 4.2e9, "Pharmaceuticals", true))
        l.add(RichPerson(997, "John Caudwell", 4.2e9, "Mobile phones", true))
        l.add(RichPerson(998, "Daniel Mate", 4.2e9, "Mining, commodities", true))
        l.add(RichPerson(999, "Gustav Magnar Witzoe", 4.2e9, "Fish farming", true))
        l.add(RichPerson(1000, "Rodger Riney & family", 4.2e9, "Discount brokerage", true))
        l.add(RichPerson(1001, "Olivier Pomel", 4.2e9, "Cloud computing", true))
        l.add(RichPerson(1002, "Samuel Tak Lee", 4.2e9, "Real estate", true))
        l.add(RichPerson(1003, "David MacNeil", 4.2e9, "Automobile accessories", true))
        l.add(RichPerson(1004, "Hilton Schlosberg & family", 4.2e9, "Energy drinks", true))
        l.add(RichPerson(1005, "Daniel Och", 4.2e9, "Hedge funds", true))
        l.add(RichPerson(1006, "Falguni Nayar", 4.2e9, "Retailing", true))
        l.add(RichPerson(1007, "Maurizio Billi", 4.2e9, "Generic drugs", true))
        l.add(RichPerson(1008, "Meg Whitman", 4.2e9, "EBay", true))
        l.add(RichPerson(1009, "Jose Joao Abdalla Filho", 4.2e9, "Investments", true))
        l.add(RichPerson(1010, "Joesley Batista", 4.2e9, "Beef processing", true))
        l.add(RichPerson(1011, "Wesley Batista", 4.2e9, "Beef packing", true))
        l.add(RichPerson(1012, "Todd Wanek", 4.1e9, "Furniture", true))
        l.add(RichPerson(1013, "Hubert Burda", 4.1e9, "Publishing", true))
        l.add(RichPerson(1014, "Roger Samuelsson", 4.1e9, "Drug delivery devices", true))
        l.add(RichPerson(1015, "Lam Wai-ying", 4.1e9, "Smartphone screens", true))
        l.add(RichPerson(1016, "Tung Chee Chen", 4.1e9, "Shipping", true))
        l.add(RichPerson(1017, "Carl Icahn", 4.1e9, "Investments", true))
        l.add(RichPerson(1018, "Jim Coulter", 4.1e9, "Private equity", true))
        l.add(RichPerson(1019, "Giuliana Benetton", 4.1e9, "Fashion retail, investments", true))
        l.add(RichPerson(1020, "Luciano Benetton", 4.1e9, "Fashion retail, investments", true))
    }

}